# Site settings
title: Copenhagen Tech Fest 2016
description: "All about Technology - All over Copenhagen - All of September"

baseurl: "http://cphtechfest.org"
exclude:
  - README.md

# Build settings
markdown: kramdown
permalink: pretty
sass:
    sass_dir: _sass
